#server:
#  port: 8761

  #http://localhost:8761 is the url where the registry will run
  #this is a registry, It should not self register eureks to itself
  
eureka:
 instance:
   hostname: ${hostname}
 client:
   service-url:
     default-zone: http://${hostname}:${server.port}
   fetch-registry: false
   register-with-eureka: false
   
spring:
  application:
    name: EUREKA-REGISTRY