
spring:
  application:
    name: COURSE-GET-SERVICE
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri : http://localhost:8080/realms/angu-project

server:
  port: 8082
  

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
      

  